apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: strapi
          image: IMAGE_BACKEND   # <-- replace with your build image
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: postgres     # <-- Service name of DB
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "strapi"
            - name: DATABASE_USERNAME
              value: "strapi"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: DATABASE_PASSWORD

            # JWT + APP KEYS
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: ADMIN_JWT_SECRET

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: JWT_SECRET

            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: API_TOKEN_SALT

            - name: APP_KEY1
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: APP_KEY1

            - name: APP_KEY2
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: APP_KEY2

            - name: APP_KEY3
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: APP_KEY3

            - name: APP_KEY4
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: APP_KEY4

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 1337
      targetPort: 1337

