# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: strapi-backend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: strapi
#   template:
#     metadata:
#       labels:
#         app: strapi
#     spec:
#       containers:
#         - name: strapi
#           image: gcr.io/gtmlabs/backend:{{TAG}}
#           ports:
#             - containerPort: 1337
#           envFrom:
#             - secretRef:
#                 name: strapi-secrets
#           env:
#             - name: NODE_ENV
#               value: "production"
#             - name: DATABASE_CLIENT
#               value: "postgres"
#             - name: DATABASE_HOST
#               value: "127.0.0.1"
#             - name: DATABASE_PORT
#               value: "5432"

#         # --- Cloud SQL Auth Proxy ---
#         - name: cloudsql-proxy
#           image: gcr.io/cloudsql-docker/gce-proxy:1.33.5
#           command:
#             - "/cloud_sql_proxy"
#             - "-instances=YOUR_PROJECT:REGION:INSTANCE_NAME=tcp:5432"
#           securityContext:
#             runAsNonRoot: true



apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          #image: 2541f4172929e9aea5fe99ed80d859a36cf7c0f1
          image: 730335385079.dkr.ecr.ap-south-1.amazonaws.com/backend-ecr-repo:2541f4172929e9aea5fe99ed80d859a36cf7c0f1
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: DATABASE_NAME

            # Strapi required keys
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: APP_KEYS
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_TOKEN_SALT
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: ADMIN_JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: JWT_SECRET
