apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
type: Opaque
stringData:
  APP_KEYS: ba93e7f9a88b4e648aa9e2d1d8b3c7ff,8c44e9a0dc4f452da9b2b6e8a09bfc3d,fc8c319a89d64c95b8e6f4420f2e7da4,b7b3a4e26bb94a09a5e6288d2f2e0d19"
  API_TOKEN_SALT: 938c47f6e3a37d66
  ADMIN_JWT_SECRET: 8fa2a7bcb6a6400a85e3a5b87d23b8c9
  JWT_SECRET: JHNKA9NVfw0Oi2VsIA06Tw==
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: strapi
  DATABASE_USERNAME: strapi
  DATABASE_PASSWORD: strapi
  
apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
  namespace: gtm-staging
type: Opaque
stringData:
  APP_KEY1: "xxxx"
  APP_KEY2: "xxxx"
  APP_KEY3: "xxxx"
  APP_KEY4: "xxxx"
  ADMIN_JWT_SECRET: "xxxx"
  JWT_SECRET: "xxxx"
  API_TOKEN_SALT: "xxxx"
  DATABASE_PASSWORD: "strapi"

