apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
type: Opaque
data:
  APP_KEYS: ba93e7f9a88b4e648aa9e2d1d8b3c7ff,8c44e9a0dc4f452da9b2b6e8a09bfc3d,fc8c319a89d64c95b8e6f4420f2e7da4,b7b3a4e26bb94a09a5e6288d2f2e0d19
  API_TOKEN_SALT: OTM4YzQ3ZjZlM2EzN2Q2Ng==
  ADMIN_JWT_SECRET: 8fa2a7bcb6a6400a85e3a5b87d23b8c9
  JWT_SECRET: JHNKA9NVfw0Oi2VsIA06Tw==
  DATABASE_HOST: cG9zdGdyZXM=  #postgres
  DATABASE_PORT: NTQzMg==      # 5432
  DATABASE_NAME: c3RyYXBp    #strapi         
  DATABASE_USERNAME: c3RyYXBp  #strapi
  DATABASE_PASSWORD: c3RyYXBp  #strapi


