apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
type: Opaque
stringData:
  APP_KEY1: "ba93e7f9a88b4e648aa9e2d1d8b3c7ff"
  APP_KEY2: "8c44e9a0dc4f452da9b2b6e8a09bfc3d"
  APP_KEY3: "fc8c319a89d64c95b8e6f4420f2e7da4"
  APP_KEY4: "b7b3a4e26bb94a09a5e6288d2f2e0d19"

  ADMIN_JWT_SECRET: "8fa2a7bcb6a6400a85e3a5b87d23b8c9"
  API_TOKEN_SALT: "OTM4YzQ3ZjZlM2EzN2Q2Ng=="
  JWT_SECRET: "JHNKA9NVfw0Oi2VsIA06Tw=="

  DATABASE_PASSWORD: "strapi"

